name = "lapce-solargraph"
version = "0.1.0"
author = "Stanislav Lapata"
display-name = "Solargraph"
description = "Solargraph for Lapce"
wasm = "bin/lapce-solargraph.wasm"

[activation]
language = ["ruby"]
workspace-contains = ["*/Gemfile", "*/*.gemspec"]
